### ISSUE TITLE
Fetch data for config_pages.

### ISSUE THREAD

**Issue by theodorosploumis** [chapter-three/next-drupal#190]
I am using module https://www.drupal.org/project/config_pages and I am looking to get data from the config_pages instances. I found a similar example at https://github.com/chapter-three/next-drupal/issues/118. 

I want to fetch data inside a Component and not in a Page. 

I tried to use `getResourceCollection` inside a `useEffect` hook but I get a `Could not fetch` error. 

Thanks.

**Comment by shadcn** [comment]
I'd probably implement an API route and a hook to fetch data inside components. Something like this:

## 1. pages/api/config/[name].ts

This API route fetches data from Drupal. This is run on the server. It is safe to use keys and make authenticated requests.

```ts
import { NextApiRequest, NextApiResponse } from "next"
import { getResourceCollection } from "next-drupal"
import { parse } from "qs"

export default async function handler(
  request: NextApiRequest,
  response: NextApiResponse
) {
  if (request.method !== "GET") {
    return response.status(405).end()
  }

  try {
    const { name, ...options } = request.query

    if (!name) {
      throw new Error("'name' missing")
    }

    const result = await getResourceCollection(
      `config_pages--${name as string}`,
      parse(options)
    )

    return response.json(result)
  } catch (error) {
    return response.status(422).end(error.message)
  }
}
```

## 2. hooks/use-config.ts

Then we can implement a custom hook for fetching data inside components. 

We're using [swr](https://swr.vercel.app/). More specifically, `useSWRImmutable`, because we want to fetch data only once on the user's first visit. We probably do not want to refetch data on every page nav.

```ts
import { JsonApiWithLocaleOptions } from "next-drupal"
import { stringify } from "qs"
import useSWRImmutable from "swr/immutable"

// This is a custom hook for fetching client-side data.
// This can be used inside components to fetch data from Drupal at runtime.
export function useConfig(name: string, options?: JsonApiWithLocaleOptions) {
  const { data, error } = useSWRImmutable(["config", name], async () => {
    const url = new URL(
      `${process.env.NEXT_PUBLIC_BASE_URL}/api/config/${name}`
    )

    if (options) {
      url.search = stringify(options)
    }

    const response = await fetch(url.toString())

    return await response.json()
  })

  return {
    config: data,
    isLoading: !error && !data,
    isError: error,
  }
}
```

## 3. Usage

Now we can use this hook inside components like this (where `site_information` is the name of the config page):

```tsx
import { useConfig } from "hooks/use-config"

export function Layout({ children }) {
  const { config } = useConfig("site_information")
}
```

Is this what you had in mind? Can you give it a try and let me know?

**Comment by theodorosploumis** [comment]
Many thanks! It works fine!

And can, also, be reused for any entity that we need to get data inside Components.

The Page from `/api/config/[name].ts` is available to anonymous users? How could we disallow access for non authorized users to this page?

**Comment by shadcn** [comment]
Do you mean unauthenticated users? Or do you want to block access from outside your domain?

**Comment by theodorosploumis** [comment]
Block unauthenticated users.

**Comment by shadcn** [comment]
Hmm I don't think there's a way to block this API route from public access unless you're authenticating your users (on the front-end), say with something like next-auth.

Right now, with no authentication, you're calling the api route in your React component which means this has to be a public call. We can't really use a private key here either since this would be exposed in the browser.

I think a possible solution would be to implement a [middleware](https://nextjs.org/docs/advanced-features/middleware) and do some check for IP and limit access.

Do you have authenticated users here or is it a public site?

**Comment by theodorosploumis** [comment]
Initially I was using a middleware but I could create a build since it is an experimental feature. I then removed it at all.

The site is public available only.

**Comment by shadcn** [comment]
I see. You could try with CORS. See https://github.com/vercel/next.js/blob/canary/examples/api-routes-cors/pages/api/cors.js
