### ISSUE TITLE
Swagger like solution for documenting APIs?

### ISSUE THREAD

**Issue by fnick851** [chapter-three/next-drupal#233]
I know with next-drupal front end developers do not work directly with the RESTful API endpoints. 

But is there a solution similar to Swagger that documents all the possible APIs that the front end can call? I think this helps if the front end developer does not work on the Drupal backend. He/she might has little knowledge and need to look up a documentation for APIs.

Thanks.

**Comment by shadcn** [comment]
Drupal has [OpenAPI](https://www.drupal.org/project/openapi) which works with [Swagger](https://www.drupal.org/project/openapi_ui_swagger).

Can you give this a try?

**Comment by devtim123** [comment]
Yes this works, but can be little slow on client browser because json:api-documentation is quite big. 

also redoc is an option, but performance is issue as well there.

for swagger-ui this patch here can be helpful the have filter option avaiable: https://www.drupal.org/project/openapi_ui_swagger/issues/3259746

what also would be nice if types can be generated with orval or something else...

**Comment by backlineint** [comment]
Closing as not planned as I think it would be out of scope for this project. We'd be better served using existing Drupal contrib solutions for this, contributing back if there are relevant areas to improve.
