### ISSUE TITLE
Error: JSON:API does not yet support resource versioning for this resource type.

### ISSUE THREAD

**Issue by Phault** [chapter-three/next-drupal#25]
Some Drupal resources do not support revisions such as taxonomy terms (at least in 8.9.6). Hence JSON:API will complain when `resourceVersion` is provided, even if it's set to `rel:latest-version` unfortunately:

```
Error: JSON:API does not yet support resource versioning for this resource type. For context, see https://www.drupal.org/project/drupal/issues/2992833#comment-12818258. To contribute, see https://www.drupal.org/project/drupal/issues/2350939 and https://www.drupal.org/project/drupal/issues/2809177.
    at /Users/cali/src/webshop-next/node_modules/next-drupal/dist/index.js:478:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getStaticProps (webpack-internal:///./pages/[...slug].tsx:92:16)
    at async Object.renderToHTML (/Users/cali/src/webshop-next/node_modules/next/dist/server/render.js:329:24)
    at async doRender (/Users/cali/src/webshop-next/node_modules/next/dist/server/next-server.js:1144:38)
    at async /Users/cali/src/webshop-next/node_modules/next/dist/server/next-server.js:1236:28
    at async /Users/cali/src/webshop-next/node_modules/next/dist/server/response-cache.js:64:36 {
  page: '/[...slug]'
}
```

This is an issue when using `getResourceByPath()`. Is there a reason it's explicitly specifying `resourceVersion=rel:latest-version` by default?

**Comment by shadcn** [comment]
This is now fixed. I added a `isVersionable` that you can use to handle revisionable entity types (aka versionable resources).

`isVersionable` is set to false by default so this should work without any config.

For backward compatibility (and since most of the time we're dealing with revisions is for `node`), this would automatically handle revisions if working with `node--` resources.

You can test this with the latest `next-drupal` and the `dev` release for `next` module.

Let me know if this works.

(I'm working on the docs)

**Comment by Phault** [comment]
Hi again,

Oh wow, I didn't expect such a quick turnaround. I've finally gotten around to testing it and it appears to be working great. Thanks a lot. 🙏
