### ISSUE TITLE
Preview Mode alters the edit path of certain entity types, showing the preview iframe instead of the edit form

### ISSUE THREAD

**Issue by camilo-escobar** [chapter-three/next-drupal#495]
I configured the Preview Mode using the "Site Selector" plugin for two entity types and their bundles:
- Custom Block - Footer (a custom bundle I created)
- Custom menu link - Custom menu link

![image](https://user-images.githubusercontent.com/2924465/236109611-e52dc54c-9544-4833-82f3-9c9503444d5c.png)

When I visit the edit URL of one of those entities, I see the preview iframe instead of the edit form, making impossible for editors to update them:
https://my-drupal-site/admin/structure/menu/item/5/edit
![image](https://user-images.githubusercontent.com/2924465/236109554-9443cc58-be33-46c0-ae5c-fb852e5ceded.png)

In other entity types and bundles (such as _node--page_) the problem is not occurring.

**Comment by shadcn** [comment]
Yes. Preview mode takes over the canonical path for the entity. For content types, this is their View page. For blocks and menus, the canonical path is the Edit page.

Preview mode is intended to be enabled for entity types that have an equivalent path on the Next.js site. Example an article on Drupal having a `/articles/path-of-article` on the Next.js site.

Is there a reason you're enabling preview mode for blocks and menus?

**Comment by jeffschuler** [comment]
I'm trying to enabling NextJS preview mode for Custom Blocks and menus because I want to send revalidation requests when the block or main menu are updated.

If I add a block entity (and a Revalidator) and don't assign a Plugin in the Preview Mode form, when trying to edit the block I get:

_Error: Call to a member function getSitesForEntity() on null in Drupal\next\Render\MainContent\HtmlRenderer->prepare()_ 

But if I do assign a site, like @camilo-escobar says, the non-working preview now obscures the block edit form.

Similar for custom menu links.

**Comment by jeffschuler** [comment]
#481  would solve this issue for me because I could keep the Revalidation for my entity type but remove all sites from Preview.. I'm not sure if @camilo-escobar actually wants preview on blocks & menu items or was just trying to mitigate the error like me.

**Comment by JohnAlbin** [comment]
Fixed by #481
