### ISSUE TITLE
Error: request to http://localhost:8080/oauth/token failed

### ISSUE THREAD

**Issue by sleepinzombie** [chapter-three/next-drupal#70]
Hello all,

I keep on having this error even though I have made every necessary configuration on Drupal side.
<img width="962" alt="Screenshot 2021-12-27 at 1 47 41 AM" src="https://user-images.githubusercontent.com/39788411/147420777-abb85c00-35a2-44ab-848a-ec5aabb5f046.png">

Please find below my `.env` configuration the Next.js app:
```
NEXT_PUBLIC_DRUPAL_BASE_URL=http://localhost:8080
NEXT_IMAGE_DOMAIN=localhost
DRUPAL_SITE_ID=next_blog
DRUPAL_PREVIEW_SECRET=secret-key
DRUPAL_CLIENT_ID=a1883d6c-bb20-4d21-a4a7-37d594e2462e
DRUPAL_CLIENT_SECRET=secret
```

For information,
My Drupal site is running on: http://localhost:8080 and
My Nextjs site is running on: http://localhost:3000.

Any help on this, please?

**Comment by sleepinzombie** [comment]
Weirdly, when I'm using the correct `DRUPAL_CLIENT_ID` and `DRUPAL_CLIENT_SECRET` via Postman, it works fine.

**Comment by SirJohn96** [comment]
Assuming the Drupal and Next.js sites are running in separate environments, the issue may be with what localhost points to. 127.0.0.1 will not be the same between the two.

Since the request made by the Next.js site is server-side, when going to localhost, it will point to itself rather than the server (or container) that has the Drupal site.

Postman is likely able to connect due to the fact that it is separate from either environment and the localhost it would be referring to is that of the host machine. So it can connect to either environment all the same much like the web browser.

I'm am not aware of a sustainable solution at the moment. However, when I encountered this issue, using DDev for my local environment, I did the following:
- In the `.ddev/config.yaml` I added entries under the `additional_hostnames` key for publicly accessible domains.
- In the same file, under `additional_fqdns`, I added an alias for use with the private network for the container. This alias matched the alias automatically set up by DDev for the web container.
The entries for both keys will automatically be added to the `/etc/hosts` file pointing to 127.0.0.1.

As an example, if the project is called `next-drupal`, here are the updates I'd add to my `.ddev/config.yaml` file:
```
additional_hostnames:
  - next-drupal  # Probably not needed by default if the project is already labeled this way.
  
additional_fqdns:
  - next-drupal-web
```

These settings will set up the following in the `/etc/hosts` file: `127.0.0.1    next-drupal.ddev.site next-drupal-web`.

`next-drupal-web` is likely the name of the web container internally. Then the `.env` file for Next.js could be: 
```
NEXT_PUBLIC_DRUPAL_BASE_URL=http://next-drupal-web
NEXT_IMAGE_DOMAIN=next-drupal.ddev.site
...
```

We technically should not need to set a host file alias for `next-drupal-web` as the containers should have this internally. However, the `NEXT_PUBLIC_DRUPAL_BASE_URL` is used for both client and server requests. If we did not add this, the client requests would fail since the alias does not exist outside the containers otherwise.

Again, I do not believe this is a sustainable solution but it has worked for me as a workaround for local development and hopefully it helps for you! Also, hopefully this can lead to a better solution. This would only be an issue with for local development.

**Comment by scotthooker** [comment]
Had same issue 

https://github.com/chapter-three/next-drupal/issues/69

**Comment by shadcn** [comment]
@sleepinzombie did you get it to work?

@SirJohn96 Can you share your `.ddev` config? I don't use DDEV but I'll see if I can reproduce this.

Thanks.

**Comment by sleepinzombie** [comment]
Hello @shadcn, I will try the solutions provided this week and revert back.
Happy New Year guys!

**Comment by scotthooker** [comment]
All works fine for me with ddev, nvm with node (16.13.1) now :)

**Comment by sleepinzombie** [comment]
Hello all, I was able to get it work. I needed to create a network for my containers in my Docker Compose file.
And add the static IPs to my `trusted_host_patterns` in `settings.php`.

Everything is working fine now.

**Comment by shadcn** [comment]
@sleepinzombie Great to hear. Thanks for the updates. Appreciate it.
